---
title: "Elucidating gene networks in resistance diffuse large B-cell lymphoma"
author: "Will Patterson"
header-includes:
  - \usepackage{mathtools}
  - \usepackage{amssymb}
  - \usepackage{amsmath}
date: "8/28/2020"
output: 
  beamer_presentation: 
    fonttheme: professionalfonts
    theme: Madrid
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Jargon: An introduction

- **Canonical variate**: linear combinations of variables
- **Canonical variate pair**: two canonical variates (one from each set) with some non-zero correlation
- **Canonical correlation**: the correlation between canonical variate pairs

## Canonical Correlation Analysis: Definition

**Canonical Correlation Analysis (CCA)** finds the relationship between two sets of variables by finding the maximally correlated linear combinations of variables.

## Canonical Correlation Analysis: Nitty Gritty

**Given**: two sets of observations on same $n$ observations, $\textbf{X}_1$ and $\textbf{X}_2$ of dimensions $n \times p_1$ and $n \times p_2$, standardized to mean zero and SD of one

**Find**: Weights $\textbf{w}_1 \in \mathbb{R}^{p_1}$ and $\textbf{w}_2 \in \mathbb{R}^{p_2}$ the objective function below is maximized

### CCA objective function
\begin{equation} \label{eq:penalized_cca}
    \text{maximize}_{w_1, w_2} \textbf{w}_1^T\textbf{X}_1^T\textbf{X}_2\textbf{w}_2 \notag \end{equation} 
\begin{equation} \text{subject to }||\textbf{w}_1||^2 \leq 1,||\textbf{w}_2||^2 \leq 1, P_1(\textbf{w}_1) \leq c_1, P_2(\textbf{w}_2) \leq c_2 \notag
\end{equation} 
\begin{center}
(where $P_1$ and $P_2$ are penalty functions, usually lasso, $L_1$)
\end{center}
## Sparse **Multiple** CCA

**Sparse multiple CCA (or sparse mCCA)** is an extensible form of sparse CCA, generalizable for any $K$ data sets $\textbf{X}_1,...,\textbf{X}_K$, where data set $k$ contains $p_k$ features. The objective function then takes the form:

### Sparse mCCA objective function
\begin{equation} \label{eq:penalized_smcca}
    \text{maximize}_{\textbf{w}_1,...,\textbf{w}_K} \sum_{i<j} \textbf{w}_i^T\textbf{X}_i^T\textbf{X}_j\textbf{w}_j \text{ subject to }||\textbf{w}_i||^2 \leq 1, P_i(\textbf{w}_i) \leq c_i, \forall i \notag
\end{equation} 

## Extension of sparse mCCA to binary outcomes

Witten and Tibshirani (2009) suggest an extension of sparse mCCA that allows for the incorporation of a two-class outcome. Their method simply treats this $\mathbb{R}^{n\times1}$ matrix as a third data set. Their objective function takes the form:

### Sparse mCCA objective function with binary variables
\begin{equation} \label{eq:penalized_smcca_with_binary}
\text{maximize}_{\textbf{w}_1, \textbf{w}_2, \textbf{w}_3} \textbf{w}_1^T\textbf{X}_1^T\textbf{X}_2\textbf{w}_2 +
    \textbf{w}_1^T\textbf{X}_1^T\textbf{y}\textbf{w}_3 +
    \textbf{w}_2^T\textbf{X}_2^T\textbf{y}\textbf{w}_3 \notag \end{equation} 
\begin{equation} \text{subject to }||\textbf{w}_i||^2 \leq 1, P_i(\textbf{w}_i) \leq c_i, \forall i \notag
\end{equation} 


